CREATE DATABASE DEMO;
USE DEMO;
CREATE TABLE DEPARTMENT(DEPT_ID CHAR(2) PRIMARY KEY,DNAME VARCHAR(20));
CREATE TABLE EMPLOYEE(EID INT PRIMARY KEY,ENAME VARCHAR(20),DEPT_ID CHAR(2),DESIGNATION VARCHAR(20),SALARY INT,DOJ DATE,
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),CHECK(SALARY>10000));
INSERT INTO DEPARTMENT VALUES('D1','SALES');
INSERT INTO DEPARTMENT VALUES('D2','MARKETING');
INSERT INTO DEPARTMENT VALUES('D3','FINANCE');
INSERT INTO EMPLOYEE VALUES(101,'SUDHA','D2','CLERK',20000,'2010-04-01');
INSERT INTO EMPLOYEE VALUES(102,'DAVID','D1','MANAGER',50000,'2018-02-18');
INSERT INTO EMPLOYEE VALUES(103,'PREETHI','D3','CLERK',35000,'2011-06-11');
INSERT INTO EMPLOYEE VALUES(104,'KIRAN','D1','SALESMAN',20000,'2014-03-07');
INSERT INTO EMPLOYEE VALUES(105,'MEENAL','D2','CLERK',50000,'2011-12-09');
INSERT INTO EMPLOYEE VALUES(106,'SUNITHA','D3','MANAGER',60000,'2018-09-18');
INSERT INTO EMPLOYEE VALUES(107,'AKHIL','D3','CLERK',25000,'2016-02-14');
INSERT INTO EMPLOYEE VALUES(108,'SUSHMA','D2','MANAGER',45000,'2012-12-31');
SELECT * FROM EMPLOYEE WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);
SELECT EID,ENAME,DNAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID=DEPARTMENT.DEPT_ID;
SELECT * FROM EMPLOYEE ORDER BY DEPT_ID ASC,SALARY DESC;
SELECT DISTINCT DESIGNATION FROM EMPLOYEE;
SELECT * FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID=DEPARTMENT.DEPT_ID WHERE DEPARTMENT.DEPT_ID='D2' AND DESIGNATION='CLERK';
SELECT * FROM EMPLOYEE WHERE DOJ>'2001-01-01';
SELECT * FROM EMPLOYEE WHERE MONTH(DOJ)=2;
SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 30000 AND 45000;
SELECT EID,ENAME,MOD(DATEDIFF(CURDATE(), DOJ), 365) AS EXP FROM EMPLOYEE;

DROP TRIGGER PREVENT;
DELIMITER $$
CREATE TRIGGER PREVENT
BEFORE DELETE
ON EMPLOYEE
FOR EACH ROW
BEGIN
	SIGNAL SQLSTATE '45000' SET message_text='NO DELETION';
END$$
DELIMITER ;
DELETE FROM EMPLOYEE WHERE EID=101;
SELECT * FROM EMPLOYEE;
CALL CALCULATE_BILL(310);