CREATE DATABASE UNIVERSITY;
USE UNIVERSITY;
CREATE TABLE STUDENT(NAME VARCHAR(30) NOT NULL,STUDENT_NUMBER INT primary key,CLASS INT,MAJOR VARCHAR(30));
CREATE TABLE COURSE(COURSE_NAME VARCHAR(50) NOT NULL,COURSE_NUMBER VARCHAR(20) PRIMARY KEY,CREDIT_HOURS INT,DEPARTMENT VARCHAR(30));
CREATE TABLE PREREQUISITE(COURSE_NUMBER VARCHAR(20),PREREQUISITE_NUMBER VARCHAR(20) PRIMARY KEY,FOREIGN KEY(COURSE_NUMBER) REFERENCES COURSE(COURSE_NUMBER));
CREATE TABLE SECTION(SECTION_IDENTIFIER INT PRIMARY KEY,COURSE_NUMBER VARCHAR(20),SEMESTER VARCHAR(30),YEAR CHAR(2),INSTRUCTOR VARCHAR(30),FOREIGN KEY(COURSE_NUMBER) REFERENCES COURSE(COURSE_NUMBER));
CREATE TABLE GRADE_REPORT(STUDENT_NUMBER INT,SECTION_IDENTIFIER INT,GRADE CHAR(1),FOREIGN KEY(STUDENT_NUMBER) references STUDENT(STUDENT_NUMBER));
ALTER TABLE GRADE_REPORT ADD CONSTRAINT FK_2 FOREIGN KEY(SECTION_IDENTIFIER) REFERENCES SECTION(SECTION_IDENTIFIER);
INSERT INTO STUDENT VALUES("SMITH",17,1,"CS"),("BROWN",8,2,"CS");
INSERT INTO COURSE VALUES("INTRO TO COMPUTER SCIENCE","CS1310",4,"CS"),("DATA STRUCTURES","CS3320",4,"CS"),
("DISCRETE MATHEMATICS","MATH2410",3,"MATH"),("DATABASE","CS3380",3,"CS");
INSERT INTO PREREQUISITE VALUES("CS3380","CS3320"),("CS3380","MATH2410"),("CS3320","CS1310");
INSERT INTO SECTION VALUES (85,"MATH2410","FALL","07","KING"),(92,"CS1310","FALL","07","ANDERSON"),
(102,"CS3320","SPRING","08","KNUTH");
INSERT INTO SECTION VALUES(112,"MATH2410","FALL","08","CHANG"),
(119,"CS1310","FALL","08","ANDERSON"),
(135,"CS3380","FALL","08","STONE");
INSERT INTO GRADE_REPORT VALUES
(17,112,"B"),
(17,119,"C"),
(8,85,"A"),
(8,92,"A"),
(8,102,"B"),
(8,135,"A");