CREATE DEFINER=`root`@`localhost` PROCEDURE `GET_GRADE`(IN MARK INT)
BEGIN
	DECLARE GRADE CHAR(1);
	IF(MARK>=90)
    THEN
		SET GRADE="A";
	ELSEIF(MARK>=80)
    THEN
		SET GRADE="B";
	ELSEIF(MARK>=70)
    THEN
		SET GRADE="C";
	ELSEIF(MARK>=60)
    THEN
		SET GRADE="E";
	ELSE
		SET GRADE="D";
	END IF;
	SELECT GRADE;	
END