USE TEST;
CREATE TABLE LOGIN(USERNAME VARCHAR(20) PRIMARY KEY,PASS VARCHAR(20));
CREATE TABLE CHANGE_ATTEMPTS(USERNAME VARCHAR(20), OLD_PASS VARCHAR(20), NEW_PASS VARCHAR(20),CHANGE_DATE DATETIME);
INSERT INTO LOGIN VALUES('ADMIN','PASS1');
CREATE TRIGGER TRACK_CHANGE
BEFORE UPDATE
ON LOGIN
FOR EACH ROW
INSERT INTO CHANGE_ATTEMPTS VALUES(OLD.USERNAME,OLD.PASS,NEW.PASS,NOW());
UPDATE LOGIN SET PASS='PASS2' WHERE USERNAME='ADMIN'; -- Changing Password for first time
UPDATE LOGIN SET PASS='PASS3' WHERE USERNAME='ADMIN'; -- Changing Password for second time
SELECT * FROM CHANGE_ATTEMPTS;