DROP DATABASE TRIGGERDEMO;
CREATE DATABASE TRIGGERDEMO;
USE TRIGGERDEMO;
CREATE TABLE CUSTOMER(CID INT PRIMARY KEY,CNAME VARCHAR(20));
CREATE TABLE STOCK(PID INT PRIMARY KEY,PNAME VARCHAR(20),STOCK INT);
CREATE TABLE SALES(CID INT,PID INT,QUANTITY INT,foreign key(CID) references CUSTOMER(CID),foreign key(PID)
references STOCK(PID));
INSERT INTO CUSTOMER values(100,'THAHIRA');
INSERT INTO CUSTOMER values(101,'ARSHA');
INSERT INTO CUSTOMER values(102,'NAZRIN');
INSERT INTO STOCK values(201,'PEN',50);
INSERT INTO STOCK values(202,'PENCIL',25);

DELIMITER $$
-- Trigger that set the maximum sale quantity to the available stock
CREATE TRIGGER CHECKSTOCK
BEFORE INSERT ON SALES
FOR EACH ROW
BEGIN
	DECLARE CURR_QUAN INT;
	SELECT STOCK INTO CURR_QUAN FROM STOCK WHERE PID=NEW.PID;
	IF(NEW.QUANTITY>CURR_QUAN)
	THEN
		SET NEW.QUANTITY=CURR_QUAN;
	END IF;
END$$

-- Trigger getting called on each sale, updating the stock column
CREATE TRIGGER UPDATESTOCK
AFTER INSERT ON SALES
FOR EACH ROW
BEGIN
	DECLARE CURR_QUAN INT;
	SELECT STOCK INTO CURR_QUAN FROM STOCK WHERE PID=NEW.PID;
	UPDATE STOCK SET STOCK=CURR_QUAN-NEW.QUANTITY WHERE PID=NEW.PID; -- updating stock on each sale for a product
END$$
DELIMITER ;
